const districts = {
  ashantiRegion: [
    'Adansi Asokwa',
    'Adansi North',
    'Adansi South',
    'Afigya Sekyere',
    'Afigya Kwabre',
    'Agogo',
    'Asante Akim North',
    'Asante Akim South',
    'Asokore Mampong',
    'Atwima Kwanwoma',
    'Atwima Nwabiagya',
    'Atwima Mponua',
    'Bosomtwe',
    'Kwabre East',
    'Kumasi Metropolitan',
    'Offinso North',
    'Offinso South',
    'Sekyere Afram Plains',
    'Sekyere East',
    'Sekyere West',
    'Suame Municipal',
    'Tano North',
    'Tano South',
    'Wassa Amenfi East',
    'Wassa Amenfi West',
    'Aboabo',
    'Asofu',
    'Asoyeboah', // Added Asoyeboah
    'Kuntanase',
    'Krofrom',
    'New Tafo',
    'Old Tafo',
    'Nhyiaeso',
    'Kumasi North',
    'Tech', // Added Tech
  ],

  greaterAccraRegion: [
    'Accra Metropolitan',
    'Ashaiman',
    'Ga Central',
    'Ga East',
    'Ga North',
    'Ga South',
    'Ga West',
    'Tema Metropolitan',
    'Kpone-Katamanso',
    'Ada East',
    'Ada West',
    'Ayawaso Central',
    'Ayawaso East',
    'Ayawaso North',
    'Ayawaso West',
    'Okaikwei North',
    'Okaikwei South',
    'Weija-Gbawe',
  ],
};

export default districts;
